[runtime]
sampler = test
root = ${PWD}
resume = T
verbosity = noisy

[test]
save_dir=output/act_dr6_lens
fatal_errors=T

[nautilus]
n_live = 1500
verbose = T

[emcee]
walkers = 64
samples = 5000
nsteps = 5


[pipeline]
; these names refer to sections later in the file:
modules = consistency camb act_dr6_lens
values = examples/act-dr6-lens-values.ini
priors = examples/act-dr6-lens-priors.ini
debug=F
timing=F
extra_output=cosmological_parameters/sigma_8 cosmological_parameters/omega_m cosmological_parameters/S_8

[act_dr6_lens]
file = ./likelihood/act-dr6-lens/act_dr6_lenslike_interface.py
like_corrections = T
variant = actplanck_baseline

[output]
filename = output/act-dr6-lens.txt

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = ./utility/consistency/consistency_interface.py
cosmomc_theta = T

[camb]
file = boltzmann/camb/camb_interface.py
mode = cmb
lmax = 4000          ;max ell to use for cmb calculation
lens_margin = 2050
lens_potential_accuracy = 8
feedback=0         ;amount of output to print
AccuracyBoost=1.0 ;CAMB accuracy boost parameter
lSampleBoost = 1.0
lAccuracyBoost = 1.2
do_tensors = T   ;include tensor modes
do_lensing = T    ;lensing is required w/ Planck data
NonLinear = none
theta_H0_range = "20 100"
halofit_version = takahashi

[cosmopower]
file = /Users/ianharrison/Dropbox/code_cdf/cosmopower-itrharrison/cosmopower/wrappers/cosmosis/cosmopower_interface.py
package_file = /Users/ianharrison/Dropbox/code_cdf/cosmopower-organization/jense_2024_emulators/jense_2023_cmb_camb_lcdm.yaml
cmb = True
lmax = 4000
matter_power_lin = False
matter_power_nl = False
debug = True
ell_factor = False
extra_renames = {'tau' : 'tau_reio', 'omega_c' : 'omega_cdm'}
